const  cars_data = [
    {
        id:1,
        carImg:'/src/assets/koenigsegg_car.png',
        status:"Koenigsegg",
        title:"Sport",
        petrol_consumption:'90L',
        manual:'Manual',
        number_of_people:'2 People',
        price:'$99.00',
        manual_icon:'/src/assets/manual_icon.svg',
        number_of_people_icon:'/src/assets/profile-2user.svg',
        petrol_consumption_icon:'/src/assets/gas-station.svg',
        old_price:'',
    },
    {
        id:2,
        carImg:'/src/assets/nissan-GT-R-car.png',
        status:"Nissan GT - R",
        title:"Sport",
        petrol_consumption:'80L',
        manual:'Manual',
        number_of_people:'2 People',
        price:'$80.00',
        old_price:'$100.00',
        manual_icon:'/src/assets/manual_icon.svg',
        number_of_people_icon:'/src/assets/profile-2user.svg',
        petrol_consumption_icon:'/src/assets/gas-station.svg',
    },
    {
        id:3,
        carImg:'/src/assets/royce-car.png',
        status:"Rolls - Royce",
        title:"Sedan",
        petrol_consumption:'70L',
        manual:'Manual',
        number_of_people:'4 People',
        price:'$96.00',
        manual_icon:'/src/assets/manual_icon.svg',
        number_of_people_icon:'/src/assets/profile-2user.svg',
        petrol_consumption_icon:'/src/assets/gas-station.svg',
        old_price:''
    },

    {
        id:4,
        carImg:'/src/assets/nissan-GT-R-car.png',
        status:"Nissan GT - R",
        title:"Sport",
        petrol_consumption:'80L',
        manual:'Manual',
        number_of_people:'2 People',
        price:'$80.00',
        old_price:'$100.00',
        manual_icon:'/src/assets/manual_icon.svg',
        number_of_people_icon:'/src/assets/profile-2user.svg',
        petrol_consumption_icon:'/src/assets/gas-station.svg',
    },
    
    {
        id:5,
        carImg:'/src/assets/all-new-rash-car.png',
        status:"All New Rush",
        title:"suv",
        petrol_consumption:'70L',
        manual:'Manual',
        number_of_people:'6 People',
        price:'$72.00',
        manual_icon:'/src/assets/manual_icon.svg',
        number_of_people_icon:'/src/assets/profile-2user.svg',
        petrol_consumption_icon:'/src/assets/gas-station.svg',
        old_price:'$80.00',
    },
    {
        id:6,
        carImg:'/src/assets/CR-V-car.png',
        status:"CR - V",
        title:"suv",
        petrol_consumption:'80L',
        manual:'Manual',
        number_of_people:'6 People',
        price:'$80.00',
        manual_icon:'/src/assets/manual_icon.svg',
        number_of_people_icon:'/src/assets/profile-2user.svg',
        petrol_consumption_icon:'/src/assets/gas-station.svg',
        
    },

    {
        id:7,
        carImg:'/src/assets/Terios-car.png',
        status:"All New Terios",
        title:"suv",
        petrol_consumption:'90L',
        manual:'Manual',
        number_of_people:'6 People',
        price:'$74.00',
        manual_icon:'/src/assets/manual_icon.svg',
        number_of_people_icon:'/src/assets/profile-2user.svg',
        petrol_consumption_icon:'/src/assets/gas-station.svg',
        old_price:''
    },
    {
        id:8,
        carImg:'/src/assets/CR-V-black-car.png',
        status:"CR - V",
        title:"suv",
        petrol_consumption:'80L',
        manual:'Manual',
        number_of_people:'6 People',
        price:'$80.00',
        manual_icon:'/src/assets/manual_icon.svg',
        number_of_people_icon:'/src/assets/profile-2user.svg',
        petrol_consumption_icon:'/src/assets/gas-station.svg',
        old_price:''
    },
    {
        id:9,
        carImg:'/src/assets/MGZX-Exclusice-car.png',
        status:"MG ZX Exclusice",
        title:"Hatchback",
        petrol_consumption:'70L',
        manual:'Manual',
        number_of_people:'4 People',
        price:'$76.00',
        old_price:'$80.00',
        manual_icon:'/src/assets/manual_icon.svg',
        number_of_people_icon:'/src/assets/profile-2user.svg',
        petrol_consumption_icon:'/src/assets/gas-station.svg',
    },
    {
        id:10,
        carImg:'/src/assets/new-MGZS-car.png',
        status:"New MG ZS",
        title:"suv",
        petrolConsumption:'80L',
        manual:'Manual',
        number_of_people:'6 People',
        price:'$80.00',
        manual_icon:'/src/assets/manual_icon.svg',
        number_of_people_icon:'/src/assets/profile-2user.svg',
        petrol_consumption_icon:'/src/assets/gas-station.svg',
        old_price:''
    },
    {
        id:11,
        carImg:'/src/assets/MGZX-Excite-car.png',
        status:"MG ZX Excite",
        title:"Hatchback",
        petrol_consumption:'90L',
        manual:'Manual',
        number_of_people:'4 People',
        price:'$74.00',
        manual_icon:'/src/assets/manual_icon.svg',
        number_of_people_icon:'/src/assets/profile-2user.svg',
        petrol_consumption_icon:'/src/assets/gas-station.svg',
        old_price:''
    },
    {
        id:12,
        carImg:'/src/assets/New-MGZS-car-2.png',
        status:"New MG ZS",
        title:"suv",
        petrolConsumption:'80L',
        manual:'Manual',
        number_of_people:'6 People',
        price:'$80.00',
        manual_icon:'/src/assets/manual_icon.svg',
        number_of_people_icon:'/src/assets/profile-2user.svg',
        petrol_consumption_icon:'/src/assets/gas-station.svg',
        old_price:''
    },
]
export default cars_data